### ISSUE TITLE
Add in-program command line

### ISSUE THREAD

**Issue by kliment** [LibrePCB/librepcb-rfcs#2]
Similar to autocad and eagle - allows both rapid tool switching to lesser-used tools that don't have their own keyboard shortcut and also entering things like coordinates precisely.

**Comment by dbrgn** [comment]
We could also take some inspiration from the command palette in VS Code:

https://www.youtube.com/watch?v=42HLszMjw7I

Plugins can also register custom commands in there. For example, here for the Rust plugin:

![screenshot](https://tmp.dbrgn.ch/2018-02-15-104608_3840x1200_scrot.png)

**Comment by ubruhin** [comment]
This issue was moved to https://librepcb.discourse.group/t/add-in-program-command-line/36
