### ISSUE TITLE
Library editor: Rotate with right-click

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-rfcs#21]
When adding new symbols to a library, the right-click right now does not seem to do anything.

For some reason, I think it would be intuitive to rotate the part using the right mouse button. Opinions?

**Comment by ubruhin** [comment]
Actually that's already implemented, and it works on my system. Could you try if it works with the nightly AppImage?

**Comment by dbrgn** [comment]
> Actually that's already implemented

Ah, that's why it seemed intuitive to me :smile: 

I found the source of confusion though. It does work in the schematic, but not in the symbol editor of the library editor (e.g. to rotate a pin).

**Comment by ubruhin** [comment]
Moved to the main repo: https://github.com/LibrePCB/LibrePCB/issues/290
