### ISSUE TITLE
text placeholder that gets filled with the component name / Device specific default value

### ISSUE THREAD

**Issue by SaculRennorb** [LibrePCB/librepcb-rfcs#25]
nothing more to say ^^

**Comment by ubruhin** [comment]
Could you explain it more detailed please? I don't understand what you mean exactly ;)

**Comment by SaculRennorb** [comment]
basically there is a placeholder for the component 'name' (`{{NAME}}`) but that just gets replaced with the abbreviation for the component plus the occurrence number eg. 'C1'
wouldn't it be good to have a placeholder that gets replaced with the name of the component int the library? a placeholder that gets replaced with for example 'PNP transistor' (the component name). I wouldn't want to use the default value for that since that gets problematic if you want to also have it for something.

also this only works on the component layer, not the more specific device layer

**Comment by ubruhin** [comment]
Ah, that's actually already possible :smiley:  You can use following placeholders:

```
{{COMPONENT}}
{{DEVICE}}
{{PACKAGE}}
```

In the schematic, this could then look like that:
![grafik](https://user-images.githubusercontent.com/5374821/45059181-6ffbea00-b09b-11e8-9119-92a0282a6ecf.png)

Note: DEVICE and PACKAGE is currently only substituted if the component is added to exactly one board.

**Comment by SaculRennorb** [comment]
oh, ok i thought i tried that and it didnt work or something, but maybe i just made a mistake.

so let me suggest something else:
some info card somewhere that shows you/lists the placeholders you can use, since i wasnt even sure if i just misstyped something or that placeholder didnt even exist

... now i just hope that doesnt already exist somewhere aswell and i just mised it alltogether...

**Comment by ubruhin** [comment]
> some info card somewhere that shows you/lists the placeholders you can use, since i wasnt even sure if i just misstyped something or that placeholder didnt even exist

Yep, that makes sense. I created a feature request for that: https://github.com/LibrePCB/LibrePCB/issues/342

I'll close this issue since the initial question is resolved ;)
