### ISSUE TITLE
toggle mode selection

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/librepcb-rfcs#29]
LibrePCB currently has two selection modes. OneHot Selection where you can select an item and it deselects all other currently selected items and Area Selection where you can select all the items within a rectangular area.

I would like to see the addition of a Toggle Selection mode. With Toggle Selection you simply change the selection status of the item between selected and unselected.  I find that most os the time I want to select an area and then go back and either add items to it or remove items from it. This would allow the user to craft the exact selection that they want.

John Eaton

**Comment by ubruhin** [comment]
Sure! As this is a pretty small issue (no RFC needed), I directly created an issue at the main repository: https://github.com/LibrePCB/LibrePCB/issues/350
