### ISSUE TITLE
CII Best Practices Badge

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/librepcb-rfcs#3]
@dbrgn wrote:
> Might be good to add the CII best practices badge to the README :)
> 
> https://bestpractices.coreinfrastructure.org/
> 
> It's quite some work to fill all the forms, but it can be done step by step.

Imported from https://github.com/LibrePCB/LibrePCB/issues/219

**Comment by dbrgn** [comment]
If I have some time, I can go through the catalogue and list the things here that would need to be changed to get more points.

(@ubruhin if you agree you can assign me this issue.)

**Comment by ubruhin** [comment]
> If I have some time, I can go through the catalogue and list the things here that would need to be changed to get more points.

:+1:

I already created the project so we have a point to start: https://bestpractices.coreinfrastructure.org/projects/1652

**Comment by ubruhin** [comment]
This issue was moved to https://librepcb.discourse.group/t/cii-best-practices-badge/15
