### ISSUE TITLE
Symbol Pins

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/librepcb-rfcs#31]
The symbol pins should have an "Invisible" property for when the pin name is not needed and would
only clutter up the schematic. This is common with digital gates.

You should also consider moving the symbol pin into a library that can be attached to either a symbol body or schematic. gEDA did this with bus rippers and  it will make it easier to deal with pins,ioports, bus spilitters and global symbols with having to rewrite code.

John Eaton

**Comment by ubruhin** [comment]
> The symbol pins should have an "Invisible" property for when the pin name is not needed and would
only clutter up the schematic. This is common with digital gates.

That's already possible (used e.g. for resistors and capacitors). But it's defined in the component symbol variant, not in the symbol itself:
![grafik](https://user-images.githubusercontent.com/5374821/47391554-5fbacf80-d71a-11e8-9e87-a6caaa77fc57.png)

> You should also consider moving the symbol pin into a library that can be attached to either a symbol body or schematic. gEDA did this with bus rippers and it will make it easier to deal with pins,ioports, bus spilitters and global symbols with having to rewrite code.

This is what you already proposed in #19, right?

**Comment by ouabache** [comment]
Found the component section and it works. Thank you.

Yes it is the same as #19, I am still lobbying for it.

**Comment by ubruhin** [comment]
OK, so I'm closing this (#19 stays still open).
