### ISSUE TITLE
Selecting Thru hole vs surface mount

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/librepcb-rfcs#36]
It appears that you must select between TH and SM when you place a component on the schematic.  You don't always know that when you are creating the schematic. I will do a lab prototype board using TH parts and individual resistors but switch to SM and resistor packs for production. I want one schematic that covers both boards.  How will that work?

John Eaton

**Comment by ubruhin** [comment]
> It appears that you must select between TH and SM when you place a component on the schematic.

Hmm actually not :) What component are you talking about?

Maybe you are confused because you *can* choose the exact device, but that's optional?

**Comment by ouabache** [comment]
I might be confused. I saw the options to select the devices but didn't realize that you could still select the component and not the devices. That will solve my problem.

Thanks

**Comment by ouabache** [comment]
I think whats throwing me for a loop is that you have one set of categories for symbols,components and devices. Packages have their own set.

I want to create a digital library so I create a cmpcat for Logic followed by Combinatorial and Registered followed by And Or Nor Nand etc followed by default and demorgan.

I fill this with all my symbols and components but when I go to select an AND2 gate I find it in Logic/Combinatorial/And but I also see selections for default and demorgan. These are not real because I make that selection as symbol variants in the AND2 component. I would rather not see them
at all because they only confuse things. 

My original problem was that I wanted to select a component but when I reached it I saw two additional
selections for devices that used that component. If I hadn't seen them I would have pick the the correct component but missed it because two devices appeared on the menu.

I have started creating top level cmpcats for symbol,component and devices to avoid this issue. You wind up with three separate trees but it keeps out the selections that you don't want to see.

John Eaton

**Comment by ubruhin** [comment]
> I might be confused. I saw the options to select the devices but didn't realize that you could still select the component and not the devices. That will solve my problem.

:+1: :smiley: 

> I fill this with all my symbols and components but when I go to select an AND2 gate I find it in Logic/Combinatorial/And but I also see selections for default and demorgan. These are not real because I make that selection as symbol variants in the AND2 component. I would rather not see them
at all because they only confuse things.

I'm not sure if I understand correctly. Is the problem only that you can see categories which only contain symbols, but no components? If yes, I planned anyway to hide categories which do not contain components (when looking for components) or symbols (when looking for symbols). Would that solve your issue?

**Comment by ouabache** [comment]
Yes,

Hiding the categories that do not contain a relevant selection would work. You would never see a selection unless it contained an appropriate selection.

The same thing might  also work with  package selection. You could merge the packages in with the rest and only display the selections that contained packages.

**Comment by ubruhin** [comment]
I opened the corresponding issue here: https://github.com/LibrePCB/LibrePCB/issues/378
