### ISSUE TITLE
Reverse engineering mode

### ISSUE THREAD

**Issue by Harvie** [LibrePCB/librepcb-rfcs#40]
If i try to create connection in "Board editor" window and that connection is not already in schematic, it gives me following error:

![image](https://user-images.githubusercontent.com/276504/49220957-f3e21b80-f3d7-11e8-86ad-f252ea9b46fc.png)

And that is perfectly OK. But what if i am reverse engineering the board. I have photos of board and i want to recreate the same board in Board editor and turn that into a schematic. (given that i've already added all the components to the schematic). That would help me to untangle the connections on the board to usable schematic...

I still think this should not be enabled by default. Surely i don't want to screw with the schematic by accidentaly adding new connections when making board from schematic. But having option to enable this mode (with proper warning dialog) would be great.

**Comment by ubruhin** [comment]
I have this use-case in mind since the beginning of LibrePCB because I also like to have this feature :) The core classes should be (more or less) ready for that feature, but the schematic and board editors aren't, so they have to be extended.

> I still think this should not be enabled by default. Surely i don't want to screw with the schematic by accidentaly adding new connections when making board from schematic. But having option to enable this mode (with proper warning dialog) would be great.

:+1:

**Comment by ubruhin** [comment]
This issue was moved to https://librepcb.discourse.group/t/reverse-engineering-mode/21
