### ISSUE TITLE
Document file format

### ISSUE THREAD

**Issue by itviewer** [LibrePCB/librepcb-rfcs#41]
Since the file format is relatively stable, in order to make it more convenient for people to contribute, we need document all file format, include schematic、pcb and  librarys.

**Comment by dbrgn** [comment]
Yes, that would be nice. In the meantime, check out [some examples](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/blob/master/cmp/2b24b18d-bd95-4fb4-8fe6-bce1d020ead4/component.lp), the s-expression based file format is very readable.

**Comment by ubruhin** [comment]
This issue was moved to https://librepcb.discourse.group/t/document-file-format/17
