### ISSUE TITLE
Community Platform

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/librepcb-rfcs#42]
I think it would be good to have some community platform besides our chat for asking questions and sharing progress. Something that is a bit more structured.

Two options come to mind: Reddit and Discourse.

## Reddit

```
+ Already has a big community, so it's easy for people to join a subreddit
+ No hosting required
+ Easy discoverability
- We don't control the data
- Less structured
+ No backups required
```

## Discourse

```
- Must be self-hosted (but that's easy)
- People have to sign up (although they can use their GitHub login for example)
+ Structured, easily searchable
+ We control the data
- We have to do backups
```

**Comment by dbrgn** [comment]
My favorite would probably be Discourse, but I guess it would be best if that wouldn't run on our API server. Which means that we don't currently have a server available, right?

Any ideas? @ubruhin if you'd also prefer Discourse, maybe we could get a 5-8€/month hosting from Hetzner or Netcup using the Patreon funds?

**Comment by ouabache** [comment]
Do both. Use Reddit for users and Discourse for developers

**Comment by ubruhin** [comment]
I would strongly prefer Discourse as it's much more structured.

Discourse [offers free hosting for open source projects](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/), maybe that would be sufficient for us?

> Do both. Use Reddit for users and Discourse for developers

That implies that the only discussion paths are user<->user and developer<->developer. But in reality there are also many discussions between users and developers, so IMHO we should have only one platform for all kinds of discussions.

Btw, with a proper discussion platform I think this RFC repository is no longer needed...

**Comment by dbrgn** [comment]
Woah, that offer looks great. I think we certainly qualify. And there's no lock-in, we can always move to self-hosted.

Could you apply?

**Comment by ouabache** [comment]
Kicad uses the split system with a users forum and a separate mailing list for developers. That keeps the developers from having to sort through all the same dumb questions that anyone who doesn't RTFM will ask. LibrePCB is small enough that a single forum will work for at least a couple of years but eventually the developers will need to create a new developers forum.

**Comment by dbrgn** [comment]
That's no problem, you can create separate subcategories, then developers can read just the developer discussions, not the user questions.

**Comment by ouabache** [comment]
Sounds good. I'll support it.

John Eaton

**Comment by ubruhin** [comment]
> Could you apply?

Done :-)

**Comment by ubruhin** [comment]
Discourse is online! https://librepcb.discourse.group/

I think it would make sense to move all issues of this repository to Discourse and archive this repository. Or what do you think?

**Comment by dbrgn** [comment]
I agree :slightly_smiling_face: I will move my own issues.

**Comment by dbrgn** [comment]
You should probably start out by defining some categories.

(I signed up btw. My usual username.)

**Comment by ubruhin** [comment]
There is a GitHub Issues to Discourse migration tool: https://www.discourse.org/github/

**Comment by dbrgn** [comment]
Oh, that's pretty cool :slightly_smiling_face:

**Comment by ubruhin** [comment]
This issue was moved to https://librepcb.discourse.group/t/community-platform/16
