### ISSUE TITLE
Download libraries manually doesn't work

### ISSUE THREAD

**Issue by ouabache** [LibrePCB/librepcb-rfcs#9]
There is a 60 char length limit on the name. Most URL's are longer

**Comment by dbrgn** [comment]
The URL is not limited, but the "local directory" path is. This is what you meant, right?

![img](https://tmp.dbrgn.ch/screenshots/20180319101511-iyn16arq.png)

I'll create a pull request to fix this.

**Comment by dbrgn** [comment]
By the way, this is something that could be reported to the LibrePCB repository. This repository is meant for discussion of larger features, not for bugreports.

**Comment by ubruhin** [comment]
I don't understand why this is an issue:
- The URL is not limited to 60 char
- The "local directory" is *not* a full path, but only a directory *name*. I think it doesn't make sense to create a directory with a name longer than 60 characters...

**Comment by ouabache** [comment]
OK My bad. I ran into this yesterday but now I can no longer reproduce it. I'll let you know if I can figure what was going on.

John Eaton

**Comment by ubruhin** [comment]
OK I'll close this issue. Just let us know if it's still an issue.
